#!/usr/bin/env python3

import sys, getopt, os, subprocess

from rofication import RoficationGui, RoficationClient

def read_xresources(prefix):
    """
    parses xrdb for rofi related parameters
    """
    props = {}
    x = subprocess.run(['xrdb', '-query'], stdout=subprocess.PIPE)
    lines = x.stdout.decode().split('\n')
    for line in filter(lambda l : l.startswith(prefix), lines):
        prop, _, value = line.partition(':\t')
        prop = prop.replace('rofi.', '')
        props[prop] = value
    return props

def dict_to_list(cfg):
    """
    convert config from dict to "command-line" string
    """
    # convert to list
    list_props = [('-'+k, v)  if not isinstance(v, bool) else ('-'+k,)
                  for k, v in cfg.items()

    ]
    # convert to flat list
    return [item for sublist in list_props for item in sublist]

if __name__ == '__main__':

    # override default_options with ones of xrdb
    cfg = read_xresources('rofi')

    cfg = dict_to_list(cfg)

    RoficationGui(cfg=cfg,
                  client=RoficationClient(sys.stdout)).run()
